package tests

import (
	"fmt"
	"math"
	"strings"
	"testing"

	aipkg "github.com/autoscan-lab/autoscan-engine/pkg/ai"
	"github.com/autoscan-lab/autoscan-engine/pkg/domain"
	"github.com/autoscan-lab/autoscan-engine/pkg/engine"
)

func scoredSubmission(t *testing.T, files map[string]string) domain.AISubmissionResult {
	t.Helper()
	sub := writeStyleSubmission(t, t.TempDir(), "example", files)
	prints := engine.FingerprintSubmissions([]domain.Submission{sub}, "lab.c", similarityConfig)
	report, err := engine.ComputeAIDetectionFromFingerprints([]domain.Submission{sub}, prints, "lab.c", nil, similarityConfig)
	if err != nil {
		t.Fatal(err)
	}
	return report.Submissions[0]
}

func TestOverallAIScoreExplainsTheTotalAndNamedFiles(t *testing.T) {
	result := scoredSubmission(t, map[string]string{"lab.c": studentStyled, "helper.c": assistantStyled})
	if result.AIScore == nil || result.AIScore.Method != "heuristic-v1" {
		t.Fatalf("missing versioned score: %+v", result)
	}
	total := 0.0
	for _, contribution := range result.AIScore.Contributions {
		total += contribution.Points
	}
	if math.Abs(total-result.AIScore.Score) > 0.001 || math.Abs(result.AIScore.Score-result.Style.Score*100) > 0.001 {
		t.Fatalf("contributions %.3f, score %.3f, style %.3f", total, result.AIScore.Score, result.Style.Score)
	}
	for _, key := range []string{"prose_comments", "doc_headers", "error_checks", "defensive_idioms"} {
		feature := styleFeature(t, result.Style, key)
		if len(feature.Locations) == 0 || feature.LocationCount < len(feature.Locations) {
			t.Fatalf("%s has no locations: %+v", key, feature)
		}
		foundHelper := false
		for _, location := range feature.Locations {
			text := map[string]string{"lab.c": studentStyled, "helper.c": assistantStyled}[location.File]
			if text == "" || location.StartLine < 1 || location.EndLine < location.StartLine || location.EndLine > len(strings.Split(text, "\n")) || location.Snippet == "" {
				t.Fatalf("invalid source location: %+v", location)
			}
			foundHelper = foundHelper || location.File == "helper.c"
		}
		if !foundHelper {
			t.Fatalf("%s lost helper.c attribution", key)
		}
	}
}

func TestOverallAIScoreAbstainsInsteadOfInventingZero(t *testing.T) {
	for _, source := range []string{"int main(void) { return 0; }", "int main( { // malformed"} {
		result := scoredSubmission(t, map[string]string{"lab.c": source})
		if result.AIScore != nil {
			t.Fatalf("insufficient parsed evidence produced score %+v", result.AIScore)
		}
	}
}

func TestOverallAIScoreUsesAttributionFloorsWithoutDuplicateBonuses(t *testing.T) {
	source := "#include <stdlib.h>\n// Generated by ChatGPT.\n// Written with Claude.\n" + studentStyled
	result := scoredSubmission(t, map[string]string{"lab.c": source, "AGENTS.md": "Local tool configuration"})
	if result.AIScore == nil || result.AIScore.Score != 90 {
		t.Fatalf("explicit attribution should set a 90-point floor: %+v", result.AIScore)
	}
	total := 0.0
	attributionCount := 0
	for _, entry := range result.AIScore.Contributions {
		total += entry.Points
		if entry.Key == "explicit_attribution" {
			attributionCount++
		}
	}
	if attributionCount != 1 || math.Abs(total-90) > 0.001 {
		t.Fatalf("duplicate attribution or inconsistent points: %+v", result.AIScore)
	}
	context := scoredSubmission(t, map[string]string{"lab.c": "#include <stdlib.h>\n// Here is the code.\n" + studentStyled})
	if math.Abs(context.AIScore.Score-context.Style.Score*100) > 0.001 {
		t.Fatalf("generic wording changed the score: %+v", context.AIScore)
	}
}

func TestStyleEvidenceIsBoundedWithoutChangingCounts(t *testing.T) {
	var source strings.Builder
	source.WriteString("int main(void) {\n")
	for i := 0; i < 80; i++ {
		fmt.Fprintf(&source, "int value%d = %d; // This sentence explains the initialized value.\n", i, i)
	}
	source.WriteString("return 0;\n}\n")
	result := scoredSubmission(t, map[string]string{"lab.c": source.String()})
	comments := styleFeature(t, result.Style, "prose_comments")
	if comments.LocationCount != 80 || len(comments.Locations) != 64 || comments.Score != 1 {
		t.Fatalf("bounded examples must preserve measured counts: %+v", comments)
	}
}

func TestOverallAIScoreExplainsDictionaryCoverage(t *testing.T) {
	sub := writeStyleSubmission(t, t.TempDir(), "example", map[string]string{"lab.c": studentStyled})
	dict := &aipkg.Dictionary{Entries: []aipkg.Entry{{ID: "example", Title: "Example pattern", Code: studentStyled}}}
	report, err := engine.ComputeAIDetectionFromFingerprints([]domain.Submission{sub}, engine.FingerprintSubmissions([]domain.Submission{sub}, "lab.c", similarityConfig), "lab.c", dict, similarityConfig)
	if err != nil {
		t.Fatal(err)
	}
	result := report.Submissions[0]
	if result.AIScore == nil || result.AIScore.Score != 100 || result.Score != 1 {
		t.Fatalf("dictionary coverage should supply the strongest floor: %+v", result)
	}
	entry := result.AIScore.Contributions[len(result.AIScore.Contributions)-1]
	if entry.Key != "dictionary" || len(entry.Locations) == 0 || entry.Locations[0].File != "lab.c" {
		t.Fatalf("dictionary locations missing: %+v", entry)
	}
}

func TestRequestedCodePatternsFlagTheExactSourceRange(t *testing.T) {
	condition := `int pick(int a, int b, int c, int d, int e) {
  if (a < 0
      || b > c
      || (b == c && d < e)) {
    return 1;
  }
  return 0;
}`
	for _, example := range []struct {
		source, kind string
		floor        float64
	}{
		{condition, "complex_condition", 20},
		{`int main(void) { char *buffer; asprintf(&buffer, "%d. Sector %d (%s) | priority=%d | landing=(%d,%d)\n",
             sector_counter + 1, current_report.sector_id, current_report.sector_name,
             current_report.priority, current_report.landing_x, current_report.landing_y); return 0; }`, "wrapped_call", 30},
		{`int main(void) { render_report("A detailed report for the selected sector with its priority and landing position",
             sector_identifier, sector_priority, sector_landing_position); return 0; }`, "wrapped_call", 30},
	} {
		result := scoredSubmission(t, map[string]string{"lab.c": example.source})
		if !result.Flagged || result.AIScore == nil || result.AIScore.Score < example.floor {
			t.Fatalf("requested pattern did not trigger review: %+v", result)
		}
		found := false
		for _, tell := range result.Tells {
			if tell.Kind == example.kind && tell.Flagged && tell.File == "lab.c" && tell.Line > 0 && tell.EndLine >= tell.Line {
				found = true
				if tell.Kind == "complex_condition" && (tell.Line != 2 || tell.EndLine != 4) {
					t.Fatalf("condition range must exclude its body: %+v", tell)
				}
			}
		}
		if !found {
			t.Fatalf("pattern has no named location: %+v", result.Tells)
		}
	}
	for _, source := range []string{
		"int main(void) { int a=0; if (a || a || a || a) return 1; return 0; }",
		"int main(void) { int a=0; if (a\n || a\n) return 1; return 0; }",
		"int main(void) { /* asprintf(&buffer, ...) */ char *text = \"asprintf\"; return 0; }",
		"int main(void) { char *buffer; asprintf(&buffer, \"%d\", 7); return 0; }",
		"int main(void) { char *buffer; asprintf(&buffer,\n \"%d\", 7); return 0; }",
		"int main(void) { render(1, /* A very long explanatory comment that must not make this short function call count as a long wrapped call in the review score. */\n 2); return 0; }",
		"#define FORMAT(p) asprintf(p, \"%d\", 1)\nint main(void) { return 0; }",
	} {
		result := scoredSubmission(t, map[string]string{"lab.c": source})
		for _, tell := range result.Tells {
			if tell.Kind == "complex_condition" || tell.Kind == "wrapped_call" {
				t.Fatalf("unrelated syntax triggered a pattern: %s %+v", source, tell)
			}
		}
	}
}

func TestSimilarityFindsRenamedRandomArraySelections(t *testing.T) {
	root := t.TempDir()
	a := writeStyleSubmission(t, root, "a", map[string]string{"lab.c": "#define TOTAL_NAMES 7\nconst char *NAMES[] = {\"One\", \"Two\"};\nvoid select_name() { char *name = NAMES[rand() % TOTAL_NAMES]; write(1, name, strlen(name)); free(name); wait(0); exit(0); }"})
	b := writeStyleSubmission(t, root, "b", map[string]string{"lab.c": "#define NUM_CHOICES 8\nconst char *choices[] = {\"Alpha\", \"Beta\"};\nvoid renamed() { const char *selection = choices[ rand ( ) % NUM_CHOICES ]; write(1, selection, strlen(selection)); free(selection); wait (0); exit (0); }"})
	subs := []domain.Submission{a, b}
	report, err := engine.ComputeSimilarityFromFingerprints(subs, engine.FingerprintSubmissions(subs, "lab.c", similarityConfig), "lab.c", similarityConfig, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Pairs) != 1 || len(report.Pairs[0].Matches) == 0 {
		t.Fatalf("renamed selection missing: %+v", report)
	}
	foundA, foundB := false, false
	for _, match := range report.Pairs[0].Matches {
		for _, span := range match.SpansA {
			foundA = foundA || strings.Contains(span.Snippet, "NAMES[rand() % TOTAL_NAMES]")
		}
		for _, span := range match.SpansB {
			foundB = foundB || strings.Contains(span.Snippet, "choices[ rand ( ) % NUM_CHOICES ]")
		}
	}
	if !foundA || !foundB {
		t.Fatalf("shared expression missing from source spans: %+v", report.Pairs[0].Matches)
	}
}
